name: learn-github-actions
on: [push]
jobs:
  create-tar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compress action step
        uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: .
          files: |
            ./project
          outPath: project.tar.gz