name: learn-github-actions
on: [push]
jobs:
  create-tar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compress action step
        uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: .
          files: |
            ./project
          outPath: project.tar.gz

      - uses: actions/upload-artifact@v2
        with:
           name: 'projekt'
           path: project.tar.gz

      - uses: actions/download-artifact@v2
        id: download
        with:
          name: 'projekt'
          path: project.tar.gz

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
